name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get service names
        id: services
        run: |
          services=$(docker-compose config --services)
          echo "services=$services" >> $GITHUB_OUTPUT

      - name: Build and push each service
        run: |
          for service in ${{ steps.services.outputs.services }}; do
            echo "Building and pushing $service"
            docker compose build $service
            docker tag $(docker-compose images -q $service) apdo60311/restaurant_system:$service-${{ github.sha }}
            docker push apdo60311/restaurant_system:$service-${{ github.sha }}
          done
