name: Docker Multi-Service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push all services
      run: |
        services=$(docker compose config --services)
        
        docker compose build
        
        for service in $services; do
          echo "Processing service: $service"
          
          docker tag restaurant_system-${service} apdo60311/restaurant_system:${service}-${{ github.sha }}
          
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker tag restaurant_system-${service} apdo60311/restaurant_system:${service}-latest
          fi
          
          docker push apdo60311/restaurant_system:${service}-${{ github.sha }}
          
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker push apdo60311/restaurant_system:${service}-latest
          fi
        done
    
    - name: Image digest
      run: |
        echo "Images pushed successfully!"
        docker images | grep apdo60311/restaurant_system
